// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	types "github.com/nicholas-fedor/watchtower/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

type MockFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilter) EXPECT() *MockFilter_Expecter {
	return &MockFilter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockFilter) Execute(_a0 types.FilterableContainer) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(types.FilterableContainer) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFilter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 types.FilterableContainer
func (_e *MockFilter_Expecter) Execute(_a0 interface{}) *MockFilter_Execute_Call {
	return &MockFilter_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockFilter_Execute_Call) Run(run func(_a0 types.FilterableContainer)) *MockFilter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.FilterableContainer))
	})
	return _c
}

func (_c *MockFilter_Execute_Call) Return(_a0 bool) *MockFilter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilter_Execute_Call) RunAndReturn(run func(types.FilterableContainer) bool) *MockFilter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilter creates a new instance of MockFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilter {
	mock := &MockFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
