// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moby/moby/api/types/image"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageInspector creates a new instance of MockImageInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageInspector {
	mock := &MockImageInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageInspector is an autogenerated mock type for the ImageInspector type
type MockImageInspector struct {
	mock.Mock
}

type MockImageInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageInspector) EXPECT() *MockImageInspector_Expecter {
	return &MockImageInspector_Expecter{mock: &_m.Mock}
}

// ImageInspectWithRaw provides a mock function for the type MockImageInspector
func (_mock *MockImageInspector) ImageInspectWithRaw(ctx context.Context, image1 string) (image.InspectResponse, []byte, error) {
	ret := _mock.Called(ctx, image1)

	if len(ret) == 0 {
		panic("no return value specified for ImageInspectWithRaw")
	}

	var r0 image.InspectResponse
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (image.InspectResponse, []byte, error)); ok {
		return returnFunc(ctx, image1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) image.InspectResponse); ok {
		r0 = returnFunc(ctx, image1)
	} else {
		r0 = ret.Get(0).(image.InspectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = returnFunc(ctx, image1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, image1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockImageInspector_ImageInspectWithRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageInspectWithRaw'
type MockImageInspector_ImageInspectWithRaw_Call struct {
	*mock.Call
}

// ImageInspectWithRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - image1 string
func (_e *MockImageInspector_Expecter) ImageInspectWithRaw(ctx interface{}, image1 interface{}) *MockImageInspector_ImageInspectWithRaw_Call {
	return &MockImageInspector_ImageInspectWithRaw_Call{Call: _e.mock.On("ImageInspectWithRaw", ctx, image1)}
}

func (_c *MockImageInspector_ImageInspectWithRaw_Call) Run(run func(ctx context.Context, image1 string)) *MockImageInspector_ImageInspectWithRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageInspector_ImageInspectWithRaw_Call) Return(inspectResponse image.InspectResponse, bytes []byte, err error) *MockImageInspector_ImageInspectWithRaw_Call {
	_c.Call.Return(inspectResponse, bytes, err)
	return _c
}

func (_c *MockImageInspector_ImageInspectWithRaw_Call) RunAndReturn(run func(ctx context.Context, image1 string) (image.InspectResponse, []byte, error)) *MockImageInspector_ImageInspectWithRaw_Call {
	_c.Call.Return(run)
	return _c
}
