// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/watchtower/pkg/types"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Close() {
	_mock.Called()
	return
}

// MockNotifier_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockNotifier_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Close() *MockNotifier_Close_Call {
	return &MockNotifier_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockNotifier_Close_Call) Run(run func()) *MockNotifier_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Close_Call) Return() *MockNotifier_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Close_Call) RunAndReturn(run func()) *MockNotifier_Close_Call {
	_c.Run(run)
	return _c
}

// GetNames provides a mock function for the type MockNotifier
func (_mock *MockNotifier) GetNames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNotifier_GetNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNames'
type MockNotifier_GetNames_Call struct {
	*mock.Call
}

// GetNames is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) GetNames() *MockNotifier_GetNames_Call {
	return &MockNotifier_GetNames_Call{Call: _e.mock.On("GetNames")}
}

func (_c *MockNotifier_GetNames_Call) Run(run func()) *MockNotifier_GetNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_GetNames_Call) Return(strings []string) *MockNotifier_GetNames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNotifier_GetNames_Call) RunAndReturn(run func() []string) *MockNotifier_GetNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockNotifier
func (_mock *MockNotifier) GetURLs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNotifier_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockNotifier_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) GetURLs() *MockNotifier_GetURLs_Call {
	return &MockNotifier_GetURLs_Call{Call: _e.mock.On("GetURLs")}
}

func (_c *MockNotifier_GetURLs_Call) Run(run func()) *MockNotifier_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_GetURLs_Call) Return(strings []string) *MockNotifier_GetURLs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNotifier_GetURLs_Call) RunAndReturn(run func() []string) *MockNotifier_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHook provides a mock function for the type MockNotifier
func (_mock *MockNotifier) RegisterHook(log *zerolog.Logger) {
	_mock.Called(log)
	return
}

// MockNotifier_RegisterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHook'
type MockNotifier_RegisterHook_Call struct {
	*mock.Call
}

// RegisterHook is a helper method to define mock.On call
//   - log *zerolog.Logger
func (_e *MockNotifier_Expecter) RegisterHook(log any) *MockNotifier_RegisterHook_Call {
	return &MockNotifier_RegisterHook_Call{Call: _e.mock.On("RegisterHook", log)}
}

func (_c *MockNotifier_RegisterHook_Call) Run(run func(log *zerolog.Logger)) *MockNotifier_RegisterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(*zerolog.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_RegisterHook_Call) Return() *MockNotifier_RegisterHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_RegisterHook_Call) RunAndReturn(run func(log *zerolog.Logger)) *MockNotifier_RegisterHook_Call {
	_c.Run(run)
	return _c
}

// SendNotification provides a mock function for the type MockNotifier
func (_mock *MockNotifier) SendNotification(report types.Report) {
	_mock.Called(report)
	return
}

// MockNotifier_SendNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNotification'
type MockNotifier_SendNotification_Call struct {
	*mock.Call
}

// SendNotification is a helper method to define mock.On call
//   - report types.Report
func (_e *MockNotifier_Expecter) SendNotification(report any) *MockNotifier_SendNotification_Call {
	return &MockNotifier_SendNotification_Call{Call: _e.mock.On("SendNotification", report)}
}

func (_c *MockNotifier_SendNotification_Call) Run(run func(report types.Report)) *MockNotifier_SendNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Report
		if args[0] != nil {
			arg0 = args[0].(types.Report)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_SendNotification_Call) Return() *MockNotifier_SendNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_SendNotification_Call) RunAndReturn(run func(report types.Report)) *MockNotifier_SendNotification_Call {
	_c.Run(run)
	return _c
}

// ShouldSendNotification provides a mock function for the type MockNotifier
func (_mock *MockNotifier) ShouldSendNotification(report types.Report) bool {
	ret := _mock.Called(report)

	if len(ret) == 0 {
		panic("no return value specified for ShouldSendNotification")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(types.Report) bool); ok {
		r0 = returnFunc(report)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNotifier_ShouldSendNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldSendNotification'
type MockNotifier_ShouldSendNotification_Call struct {
	*mock.Call
}

// ShouldSendNotification is a helper method to define mock.On call
//   - report types.Report
func (_e *MockNotifier_Expecter) ShouldSendNotification(report any) *MockNotifier_ShouldSendNotification_Call {
	return &MockNotifier_ShouldSendNotification_Call{Call: _e.mock.On("ShouldSendNotification", report)}
}

func (_c *MockNotifier_ShouldSendNotification_Call) Run(run func(report types.Report)) *MockNotifier_ShouldSendNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Report
		if args[0] != nil {
			arg0 = args[0].(types.Report)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_ShouldSendNotification_Call) Return(b bool) *MockNotifier_ShouldSendNotification_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNotifier_ShouldSendNotification_Call) RunAndReturn(run func(report types.Report) bool) *MockNotifier_ShouldSendNotification_Call {
	_c.Call.Return(run)
	return _c
}

// StartNotification provides a mock function for the type MockNotifier
func (_mock *MockNotifier) StartNotification(suppressSummary bool) {
	_mock.Called(suppressSummary)
	return
}

// MockNotifier_StartNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNotification'
type MockNotifier_StartNotification_Call struct {
	*mock.Call
}

// StartNotification is a helper method to define mock.On call
//   - suppressSummary bool
func (_e *MockNotifier_Expecter) StartNotification(suppressSummary any) *MockNotifier_StartNotification_Call {
	return &MockNotifier_StartNotification_Call{Call: _e.mock.On("StartNotification", suppressSummary)}
}

func (_c *MockNotifier_StartNotification_Call) Run(run func(suppressSummary bool)) *MockNotifier_StartNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_StartNotification_Call) Return() *MockNotifier_StartNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_StartNotification_Call) RunAndReturn(run func(suppressSummary bool)) *MockNotifier_StartNotification_Call {
	_c.Run(run)
	return _c
}
