// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/moby/moby/api/types/container"
	"github.com/nicholas-fedor/watchtower/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CheckContainerUpdate provides a mock function for the type MockClient
func (_mock *MockClient) CheckContainerUpdate(ctx context.Context, container types.Container, params types.UpdateParams) (bool, types.ImageID, string, error) {
	ret := _mock.Called(ctx, container, params)

	if len(ret) == 0 {
		panic("no return value specified for CheckContainerUpdate")
	}

	var r0 bool
	var r1 types.ImageID
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, types.UpdateParams) (bool, types.ImageID, string, error)); ok {
		return returnFunc(ctx, container, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, types.UpdateParams) bool); ok {
		r0 = returnFunc(ctx, container, params)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container, types.UpdateParams) types.ImageID); ok {
		r1 = returnFunc(ctx, container, params)
	} else {
		r1 = ret.Get(1).(types.ImageID)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, types.Container, types.UpdateParams) string); ok {
		r2 = returnFunc(ctx, container, params)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, types.Container, types.UpdateParams) error); ok {
		r3 = returnFunc(ctx, container, params)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockClient_CheckContainerUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckContainerUpdate'
type MockClient_CheckContainerUpdate_Call struct {
	*mock.Call
}

// CheckContainerUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - params types.UpdateParams
func (_e *MockClient_Expecter) CheckContainerUpdate(ctx any, container any, params any) *MockClient_CheckContainerUpdate_Call {
	return &MockClient_CheckContainerUpdate_Call{Call: _e.mock.On("CheckContainerUpdate", ctx, container, params)}
}

func (_c *MockClient_CheckContainerUpdate_Call) Run(run func(ctx context.Context, container types.Container, params types.UpdateParams)) *MockClient_CheckContainerUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 types.UpdateParams
		if args[2] != nil {
			arg2 = args[2].(types.UpdateParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CheckContainerUpdate_Call) Return(b bool, imageID types.ImageID, s string, err error) *MockClient_CheckContainerUpdate_Call {
	_c.Call.Return(b, imageID, s, err)
	return _c
}

func (_c *MockClient_CheckContainerUpdate_Call) RunAndReturn(run func(ctx context.Context, container types.Container, params types.UpdateParams) (bool, types.ImageID, string, error)) *MockClient_CheckContainerUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContainer provides a mock function for the type MockClient
func (_mock *MockClient) CreateContainer(ctx context.Context, container types.Container) (types.ContainerID, error) {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 types.ContainerID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) (types.ContainerID, error)); ok {
		return returnFunc(ctx, container)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) types.ContainerID); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Get(0).(types.ContainerID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container) error); ok {
		r1 = returnFunc(ctx, container)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContainer'
type MockClient_CreateContainer_Call struct {
	*mock.Call
}

// CreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
func (_e *MockClient_Expecter) CreateContainer(ctx any, container any) *MockClient_CreateContainer_Call {
	return &MockClient_CreateContainer_Call{Call: _e.mock.On("CreateContainer", ctx, container)}
}

func (_c *MockClient_CreateContainer_Call) Run(run func(ctx context.Context, container types.Container)) *MockClient_CreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_CreateContainer_Call) Return(containerID types.ContainerID, err error) *MockClient_CreateContainer_Call {
	_c.Call.Return(containerID, err)
	return _c
}

func (_c *MockClient_CreateContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container) (types.ContainerID, error)) *MockClient_CreateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEphemeralOrchestrator provides a mock function for the type MockClient
func (_mock *MockClient) CreateEphemeralOrchestrator(ctx context.Context, sourceContainer types.Container, newImage string, containerChain string, cleanup bool) (types.ContainerID, error) {
	ret := _mock.Called(ctx, sourceContainer, newImage, containerChain, cleanup)

	if len(ret) == 0 {
		panic("no return value specified for CreateEphemeralOrchestrator")
	}

	var r0 types.ContainerID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, string, string, bool) (types.ContainerID, error)); ok {
		return returnFunc(ctx, sourceContainer, newImage, containerChain, cleanup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, string, string, bool) types.ContainerID); ok {
		r0 = returnFunc(ctx, sourceContainer, newImage, containerChain, cleanup)
	} else {
		r0 = ret.Get(0).(types.ContainerID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container, string, string, bool) error); ok {
		r1 = returnFunc(ctx, sourceContainer, newImage, containerChain, cleanup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateEphemeralOrchestrator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEphemeralOrchestrator'
type MockClient_CreateEphemeralOrchestrator_Call struct {
	*mock.Call
}

// CreateEphemeralOrchestrator is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceContainer types.Container
//   - newImage string
//   - containerChain string
//   - cleanup bool
func (_e *MockClient_Expecter) CreateEphemeralOrchestrator(ctx any, sourceContainer any, newImage any, containerChain any, cleanup any) *MockClient_CreateEphemeralOrchestrator_Call {
	return &MockClient_CreateEphemeralOrchestrator_Call{Call: _e.mock.On("CreateEphemeralOrchestrator", ctx, sourceContainer, newImage, containerChain, cleanup)}
}

func (_c *MockClient_CreateEphemeralOrchestrator_Call) Run(run func(ctx context.Context, sourceContainer types.Container, newImage string, containerChain string, cleanup bool)) *MockClient_CreateEphemeralOrchestrator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_CreateEphemeralOrchestrator_Call) Return(containerID types.ContainerID, err error) *MockClient_CreateEphemeralOrchestrator_Call {
	_c.Call.Return(containerID, err)
	return _c
}

func (_c *MockClient_CreateEphemeralOrchestrator_Call) RunAndReturn(run func(ctx context.Context, sourceContainer types.Container, newImage string, containerChain string, cleanup bool) (types.ContainerID, error)) *MockClient_CreateEphemeralOrchestrator_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCommand provides a mock function for the type MockClient
func (_mock *MockClient) ExecuteCommand(ctx context.Context, container types.Container, command string, timeout int, uid int, gid int) (bool, error) {
	ret := _mock.Called(ctx, container, command, timeout, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, string, int, int, int) (bool, error)); ok {
		return returnFunc(ctx, container, command, timeout, uid, gid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, string, int, int, int) bool); ok {
		r0 = returnFunc(ctx, container, command, timeout, uid, gid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container, string, int, int, int) error); ok {
		r1 = returnFunc(ctx, container, command, timeout, uid, gid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ExecuteCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommand'
type MockClient_ExecuteCommand_Call struct {
	*mock.Call
}

// ExecuteCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - command string
//   - timeout int
//   - uid int
//   - gid int
func (_e *MockClient_Expecter) ExecuteCommand(ctx any, container any, command any, timeout any, uid any, gid any) *MockClient_ExecuteCommand_Call {
	return &MockClient_ExecuteCommand_Call{Call: _e.mock.On("ExecuteCommand", ctx, container, command, timeout, uid, gid)}
}

func (_c *MockClient_ExecuteCommand_Call) Run(run func(ctx context.Context, container types.Container, command string, timeout int, uid int, gid int)) *MockClient_ExecuteCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) Return(b bool, err error) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) RunAndReturn(run func(ctx context.Context, container types.Container, command string, timeout int, uid int, gid int) (bool, error)) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainer provides a mock function for the type MockClient
func (_mock *MockClient) GetContainer(ctx context.Context, containerID types.ContainerID) (types.Container, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 types.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID) (types.Container, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID) types.Container); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.ContainerID) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type MockClient_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID types.ContainerID
func (_e *MockClient_Expecter) GetContainer(ctx any, containerID any) *MockClient_GetContainer_Call {
	return &MockClient_GetContainer_Call{Call: _e.mock.On("GetContainer", ctx, containerID)}
}

func (_c *MockClient_GetContainer_Call) Run(run func(ctx context.Context, containerID types.ContainerID)) *MockClient_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.ContainerID
		if args[1] != nil {
			arg1 = args[1].(types.ContainerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetContainer_Call) Return(container types.Container, err error) *MockClient_GetContainer_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockClient_GetContainer_Call) RunAndReturn(run func(ctx context.Context, containerID types.ContainerID) (types.Container, error)) *MockClient_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentWatchtowerContainer provides a mock function for the type MockClient
func (_mock *MockClient) GetCurrentWatchtowerContainer(ctx context.Context, containerID types.ContainerID) (types.Container, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWatchtowerContainer")
	}

	var r0 types.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID) (types.Container, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID) types.Container); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.ContainerID) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetCurrentWatchtowerContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWatchtowerContainer'
type MockClient_GetCurrentWatchtowerContainer_Call struct {
	*mock.Call
}

// GetCurrentWatchtowerContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID types.ContainerID
func (_e *MockClient_Expecter) GetCurrentWatchtowerContainer(ctx any, containerID any) *MockClient_GetCurrentWatchtowerContainer_Call {
	return &MockClient_GetCurrentWatchtowerContainer_Call{Call: _e.mock.On("GetCurrentWatchtowerContainer", ctx, containerID)}
}

func (_c *MockClient_GetCurrentWatchtowerContainer_Call) Run(run func(ctx context.Context, containerID types.ContainerID)) *MockClient_GetCurrentWatchtowerContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.ContainerID
		if args[1] != nil {
			arg1 = args[1].(types.ContainerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetCurrentWatchtowerContainer_Call) Return(container types.Container, err error) *MockClient_GetCurrentWatchtowerContainer_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockClient_GetCurrentWatchtowerContainer_Call) RunAndReturn(run func(ctx context.Context, containerID types.ContainerID) (types.Container, error)) *MockClient_GetCurrentWatchtowerContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageDiskUsage provides a mock function for the type MockClient
func (_mock *MockClient) GetImageDiskUsage(ctx context.Context) (types.ImageDiskUsage, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImageDiskUsage")
	}

	var r0 types.ImageDiskUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (types.ImageDiskUsage, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) types.ImageDiskUsage); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(types.ImageDiskUsage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetImageDiskUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageDiskUsage'
type MockClient_GetImageDiskUsage_Call struct {
	*mock.Call
}

// GetImageDiskUsage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetImageDiskUsage(ctx any) *MockClient_GetImageDiskUsage_Call {
	return &MockClient_GetImageDiskUsage_Call{Call: _e.mock.On("GetImageDiskUsage", ctx)}
}

func (_c *MockClient_GetImageDiskUsage_Call) Run(run func(ctx context.Context)) *MockClient_GetImageDiskUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetImageDiskUsage_Call) Return(imageDiskUsage types.ImageDiskUsage, err error) *MockClient_GetImageDiskUsage_Call {
	_c.Call.Return(imageDiskUsage, err)
	return _c
}

func (_c *MockClient_GetImageDiskUsage_Call) RunAndReturn(run func(ctx context.Context) (types.ImageDiskUsage, error)) *MockClient_GetImageDiskUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function for the type MockClient
func (_mock *MockClient) GetInfo(ctx context.Context) (map[string]any, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]any, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]any); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockClient_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetInfo(ctx any) *MockClient_GetInfo_Call {
	return &MockClient_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx)}
}

func (_c *MockClient_GetInfo_Call) Run(run func(ctx context.Context)) *MockClient_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetInfo_Call) Return(stringToAnyMoqParam map[string]any, err error) *MockClient_GetInfo_Call {
	_c.Call.Return(stringToAnyMoqParam, err)
	return _c
}

func (_c *MockClient_GetInfo_Call) RunAndReturn(run func(ctx context.Context) (map[string]any, error)) *MockClient_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockClient
func (_mock *MockClient) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockClient_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetVersion() *MockClient_GetVersion_Call {
	return &MockClient_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockClient_GetVersion_Call) Run(run func()) *MockClient_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetVersion_Call) Return(s string) *MockClient_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_GetVersion_Call) RunAndReturn(run func() string) *MockClient_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsContainerStale provides a mock function for the type MockClient
func (_mock *MockClient) IsContainerStale(ctx context.Context, container types.Container, params types.UpdateParams) (bool, types.ImageID, string, error) {
	ret := _mock.Called(ctx, container, params)

	if len(ret) == 0 {
		panic("no return value specified for IsContainerStale")
	}

	var r0 bool
	var r1 types.ImageID
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, types.UpdateParams) (bool, types.ImageID, string, error)); ok {
		return returnFunc(ctx, container, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, types.UpdateParams) bool); ok {
		r0 = returnFunc(ctx, container, params)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container, types.UpdateParams) types.ImageID); ok {
		r1 = returnFunc(ctx, container, params)
	} else {
		r1 = ret.Get(1).(types.ImageID)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, types.Container, types.UpdateParams) string); ok {
		r2 = returnFunc(ctx, container, params)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, types.Container, types.UpdateParams) error); ok {
		r3 = returnFunc(ctx, container, params)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockClient_IsContainerStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsContainerStale'
type MockClient_IsContainerStale_Call struct {
	*mock.Call
}

// IsContainerStale is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - params types.UpdateParams
func (_e *MockClient_Expecter) IsContainerStale(ctx any, container any, params any) *MockClient_IsContainerStale_Call {
	return &MockClient_IsContainerStale_Call{Call: _e.mock.On("IsContainerStale", ctx, container, params)}
}

func (_c *MockClient_IsContainerStale_Call) Run(run func(ctx context.Context, container types.Container, params types.UpdateParams)) *MockClient_IsContainerStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 types.UpdateParams
		if args[2] != nil {
			arg2 = args[2].(types.UpdateParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_IsContainerStale_Call) Return(b bool, imageID types.ImageID, s string, err error) *MockClient_IsContainerStale_Call {
	_c.Call.Return(b, imageID, s, err)
	return _c
}

func (_c *MockClient_IsContainerStale_Call) RunAndReturn(run func(ctx context.Context, container types.Container, params types.UpdateParams) (bool, types.ImageID, string, error)) *MockClient_IsContainerStale_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockClient
func (_mock *MockClient) ListContainers(ctx context.Context, filter ...types.Filter) ([]types.Container, error) {
	var tmpRet mock.Arguments
	if len(filter) > 0 {
		tmpRet = _mock.Called(ctx, filter)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []types.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...types.Filter) ([]types.Container, error)); ok {
		return returnFunc(ctx, filter...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...types.Filter) []types.Container); ok {
		r0 = returnFunc(ctx, filter...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...types.Filter) error); ok {
		r1 = returnFunc(ctx, filter...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockClient_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ...types.Filter
func (_e *MockClient_Expecter) ListContainers(ctx any, filter ...any) *MockClient_ListContainers_Call {
	return &MockClient_ListContainers_Call{Call: _e.mock.On("ListContainers",
		append([]any{ctx}, filter...)...)}
}

func (_c *MockClient_ListContainers_Call) Run(run func(ctx context.Context, filter ...types.Filter)) *MockClient_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.Filter
		var variadicArgs []types.Filter
		if len(args) > 1 {
			variadicArgs = args[1].([]types.Filter)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_ListContainers_Call) Return(containers []types.Container, err error) *MockClient_ListContainers_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *MockClient_ListContainers_Call) RunAndReturn(run func(ctx context.Context, filter ...types.Filter) ([]types.Container, error)) *MockClient_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockClient
func (_mock *MockClient) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Ping(ctx any) *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockClient_Ping_Call) Run(run func(ctx context.Context)) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(err error) *MockClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function for the type MockClient
func (_mock *MockClient) RemoveContainer(ctx context.Context, container types.Container) error {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) error); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockClient_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
func (_e *MockClient_Expecter) RemoveContainer(ctx any, container any) *MockClient_RemoveContainer_Call {
	return &MockClient_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", ctx, container)}
}

func (_c *MockClient_RemoveContainer_Call) Run(run func(ctx context.Context, container types.Container)) *MockClient_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RemoveContainer_Call) Return(err error) *MockClient_RemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RemoveContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container) error) *MockClient_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImageByID provides a mock function for the type MockClient
func (_mock *MockClient) RemoveImageByID(ctx context.Context, imageID types.ImageID, imageName string) error {
	ret := _mock.Called(ctx, imageID, imageName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImageByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ImageID, string) error); ok {
		r0 = returnFunc(ctx, imageID, imageName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RemoveImageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImageByID'
type MockClient_RemoveImageByID_Call struct {
	*mock.Call
}

// RemoveImageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID types.ImageID
//   - imageName string
func (_e *MockClient_Expecter) RemoveImageByID(ctx any, imageID any, imageName any) *MockClient_RemoveImageByID_Call {
	return &MockClient_RemoveImageByID_Call{Call: _e.mock.On("RemoveImageByID", ctx, imageID, imageName)}
}

func (_c *MockClient_RemoveImageByID_Call) Run(run func(ctx context.Context, imageID types.ImageID, imageName string)) *MockClient_RemoveImageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.ImageID
		if args[1] != nil {
			arg1 = args[1].(types.ImageID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RemoveImageByID_Call) Return(err error) *MockClient_RemoveImageByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RemoveImageByID_Call) RunAndReturn(run func(ctx context.Context, imageID types.ImageID, imageName string) error) *MockClient_RemoveImageByID_Call {
	_c.Call.Return(run)
	return _c
}

// RenameContainer provides a mock function for the type MockClient
func (_mock *MockClient) RenameContainer(ctx context.Context, container types.Container, newName string) error {
	ret := _mock.Called(ctx, container, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, string) error); ok {
		r0 = returnFunc(ctx, container, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RenameContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameContainer'
type MockClient_RenameContainer_Call struct {
	*mock.Call
}

// RenameContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - newName string
func (_e *MockClient_Expecter) RenameContainer(ctx any, container any, newName any) *MockClient_RenameContainer_Call {
	return &MockClient_RenameContainer_Call{Call: _e.mock.On("RenameContainer", ctx, container, newName)}
}

func (_c *MockClient_RenameContainer_Call) Run(run func(ctx context.Context, container types.Container, newName string)) *MockClient_RenameContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RenameContainer_Call) Return(err error) *MockClient_RenameContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RenameContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container, newName string) error) *MockClient_RenameContainer_Call {
	_c.Call.Return(run)
	return _c
}

// SetNoRestartPolicy provides a mock function for the type MockClient
func (_mock *MockClient) SetNoRestartPolicy(ctx context.Context, container types.Container) {
	_mock.Called(ctx, container)
	return
}

// MockClient_SetNoRestartPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNoRestartPolicy'
type MockClient_SetNoRestartPolicy_Call struct {
	*mock.Call
}

// SetNoRestartPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
func (_e *MockClient_Expecter) SetNoRestartPolicy(ctx any, container any) *MockClient_SetNoRestartPolicy_Call {
	return &MockClient_SetNoRestartPolicy_Call{Call: _e.mock.On("SetNoRestartPolicy", ctx, container)}
}

func (_c *MockClient_SetNoRestartPolicy_Call) Run(run func(ctx context.Context, container types.Container)) *MockClient_SetNoRestartPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_SetNoRestartPolicy_Call) Return() *MockClient_SetNoRestartPolicy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetNoRestartPolicy_Call) RunAndReturn(run func(ctx context.Context, container types.Container)) *MockClient_SetNoRestartPolicy_Call {
	_c.Run(run)
	return _c
}

// StartContainer provides a mock function for the type MockClient
func (_mock *MockClient) StartContainer(ctx context.Context, container types.Container) (types.ContainerID, error) {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 types.ContainerID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) (types.ContainerID, error)); ok {
		return returnFunc(ctx, container)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) types.ContainerID); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Get(0).(types.ContainerID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Container) error); ok {
		r1 = returnFunc(ctx, container)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockClient_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
func (_e *MockClient_Expecter) StartContainer(ctx any, container any) *MockClient_StartContainer_Call {
	return &MockClient_StartContainer_Call{Call: _e.mock.On("StartContainer", ctx, container)}
}

func (_c *MockClient_StartContainer_Call) Run(run func(ctx context.Context, container types.Container)) *MockClient_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_StartContainer_Call) Return(containerID types.ContainerID, err error) *MockClient_StartContainer_Call {
	_c.Call.Return(containerID, err)
	return _c
}

func (_c *MockClient_StartContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container) (types.ContainerID, error)) *MockClient_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainerByID provides a mock function for the type MockClient
func (_mock *MockClient) StartContainerByID(ctx context.Context, containerID types.ContainerID) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for StartContainerByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StartContainerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainerByID'
type MockClient_StartContainerByID_Call struct {
	*mock.Call
}

// StartContainerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID types.ContainerID
func (_e *MockClient_Expecter) StartContainerByID(ctx any, containerID any) *MockClient_StartContainerByID_Call {
	return &MockClient_StartContainerByID_Call{Call: _e.mock.On("StartContainerByID", ctx, containerID)}
}

func (_c *MockClient_StartContainerByID_Call) Run(run func(ctx context.Context, containerID types.ContainerID)) *MockClient_StartContainerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.ContainerID
		if args[1] != nil {
			arg1 = args[1].(types.ContainerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_StartContainerByID_Call) Return(err error) *MockClient_StartContainerByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StartContainerByID_Call) RunAndReturn(run func(ctx context.Context, containerID types.ContainerID) error) *MockClient_StartContainerByID_Call {
	_c.Call.Return(run)
	return _c
}

// StopAndRemoveContainer provides a mock function for the type MockClient
func (_mock *MockClient) StopAndRemoveContainer(ctx context.Context, container types.Container, timeout time.Duration) error {
	ret := _mock.Called(ctx, container, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopAndRemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, time.Duration) error); ok {
		r0 = returnFunc(ctx, container, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopAndRemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAndRemoveContainer'
type MockClient_StopAndRemoveContainer_Call struct {
	*mock.Call
}

// StopAndRemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - timeout time.Duration
func (_e *MockClient_Expecter) StopAndRemoveContainer(ctx any, container any, timeout any) *MockClient_StopAndRemoveContainer_Call {
	return &MockClient_StopAndRemoveContainer_Call{Call: _e.mock.On("StopAndRemoveContainer", ctx, container, timeout)}
}

func (_c *MockClient_StopAndRemoveContainer_Call) Run(run func(ctx context.Context, container types.Container, timeout time.Duration)) *MockClient_StopAndRemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StopAndRemoveContainer_Call) Return(err error) *MockClient_StopAndRemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopAndRemoveContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container, timeout time.Duration) error) *MockClient_StopAndRemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function for the type MockClient
func (_mock *MockClient) StopContainer(ctx context.Context, container types.Container, timeout time.Duration) error {
	ret := _mock.Called(ctx, container, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, time.Duration) error); ok {
		r0 = returnFunc(ctx, container, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockClient_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
//   - timeout time.Duration
func (_e *MockClient_Expecter) StopContainer(ctx any, container any, timeout any) *MockClient_StopContainer_Call {
	return &MockClient_StopContainer_Call{Call: _e.mock.On("StopContainer", ctx, container, timeout)}
}

func (_c *MockClient_StopContainer_Call) Run(run func(ctx context.Context, container types.Container, timeout time.Duration)) *MockClient_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StopContainer_Call) Return(err error) *MockClient_StopContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopContainer_Call) RunAndReturn(run func(ctx context.Context, container types.Container, timeout time.Duration) error) *MockClient_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContainer provides a mock function for the type MockClient
func (_mock *MockClient) UpdateContainer(ctx context.Context, container1 types.Container, config container.UpdateConfig) error {
	ret := _mock.Called(ctx, container1, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container, container.UpdateConfig) error); ok {
		r0 = returnFunc(ctx, container1, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContainer'
type MockClient_UpdateContainer_Call struct {
	*mock.Call
}

// UpdateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - container1 types.Container
//   - config container.UpdateConfig
func (_e *MockClient_Expecter) UpdateContainer(ctx any, container1 any, config any) *MockClient_UpdateContainer_Call {
	return &MockClient_UpdateContainer_Call{Call: _e.mock.On("UpdateContainer", ctx, container1, config)}
}

func (_c *MockClient_UpdateContainer_Call) Run(run func(ctx context.Context, container1 types.Container, config container.UpdateConfig)) *MockClient_UpdateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		var arg2 container.UpdateConfig
		if args[2] != nil {
			arg2 = args[2].(container.UpdateConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_UpdateContainer_Call) Return(err error) *MockClient_UpdateContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateContainer_Call) RunAndReturn(run func(ctx context.Context, container1 types.Container, config container.UpdateConfig) error) *MockClient_UpdateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForContainerHealthy provides a mock function for the type MockClient
func (_mock *MockClient) WaitForContainerHealthy(ctx context.Context, containerID types.ContainerID, timeout time.Duration) error {
	ret := _mock.Called(ctx, containerID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForContainerHealthy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.ContainerID, time.Duration) error); ok {
		r0 = returnFunc(ctx, containerID, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_WaitForContainerHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForContainerHealthy'
type MockClient_WaitForContainerHealthy_Call struct {
	*mock.Call
}

// WaitForContainerHealthy is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID types.ContainerID
//   - timeout time.Duration
func (_e *MockClient_Expecter) WaitForContainerHealthy(ctx any, containerID any, timeout any) *MockClient_WaitForContainerHealthy_Call {
	return &MockClient_WaitForContainerHealthy_Call{Call: _e.mock.On("WaitForContainerHealthy", ctx, containerID, timeout)}
}

func (_c *MockClient_WaitForContainerHealthy_Call) Run(run func(ctx context.Context, containerID types.ContainerID, timeout time.Duration)) *MockClient_WaitForContainerHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.ContainerID
		if args[1] != nil {
			arg1 = args[1].(types.ContainerID)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_WaitForContainerHealthy_Call) Return(err error) *MockClient_WaitForContainerHealthy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_WaitForContainerHealthy_Call) RunAndReturn(run func(ctx context.Context, containerID types.ContainerID, timeout time.Duration) error) *MockClient_WaitForContainerHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// WarnOnHeadPullFailed provides a mock function for the type MockClient
func (_mock *MockClient) WarnOnHeadPullFailed(container1 types.Container) bool {
	ret := _mock.Called(container1)

	if len(ret) == 0 {
		panic("no return value specified for WarnOnHeadPullFailed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(types.Container) bool); ok {
		r0 = returnFunc(container1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClient_WarnOnHeadPullFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnOnHeadPullFailed'
type MockClient_WarnOnHeadPullFailed_Call struct {
	*mock.Call
}

// WarnOnHeadPullFailed is a helper method to define mock.On call
//   - container1 types.Container
func (_e *MockClient_Expecter) WarnOnHeadPullFailed(container1 any) *MockClient_WarnOnHeadPullFailed_Call {
	return &MockClient_WarnOnHeadPullFailed_Call{Call: _e.mock.On("WarnOnHeadPullFailed", container1)}
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) Run(run func(container1 types.Container)) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Container
		if args[0] != nil {
			arg0 = args[0].(types.Container)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) Return(b bool) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) RunAndReturn(run func(container1 types.Container) bool) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Return(run)
	return _c
}
