// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperations creates a new instance of MockOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperations {
	mock := &MockOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperations is an autogenerated mock type for the Operations type
type MockOperations struct {
	mock.Mock
}

type MockOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperations) EXPECT() *MockOperations_Expecter {
	return &MockOperations_Expecter{mock: &_m.Mock}
}

// ContainerCreate provides a mock function for the type MockOperations
func (_mock *MockOperations) ContainerCreate(ctx context.Context, options client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerCreate")
	}

	var r0 client.ContainerCreateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) (client.ContainerCreateResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) client.ContainerCreateResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ContainerCreateResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ContainerCreateOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_ContainerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCreate'
type MockOperations_ContainerCreate_Call struct {
	*mock.Call
}

// ContainerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - options client.ContainerCreateOptions
func (_e *MockOperations_Expecter) ContainerCreate(ctx any, options any) *MockOperations_ContainerCreate_Call {
	return &MockOperations_ContainerCreate_Call{Call: _e.mock.On("ContainerCreate", ctx, options)}
}

func (_c *MockOperations_ContainerCreate_Call) Run(run func(ctx context.Context, options client.ContainerCreateOptions)) *MockOperations_ContainerCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ContainerCreateOptions
		if args[1] != nil {
			arg1 = args[1].(client.ContainerCreateOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperations_ContainerCreate_Call) Return(containerCreateResult client.ContainerCreateResult, err error) *MockOperations_ContainerCreate_Call {
	_c.Call.Return(containerCreateResult, err)
	return _c
}

func (_c *MockOperations_ContainerCreate_Call) RunAndReturn(run func(ctx context.Context, options client.ContainerCreateOptions) (client.ContainerCreateResult, error)) *MockOperations_ContainerCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerInspect provides a mock function for the type MockOperations
func (_mock *MockOperations) ContainerInspect(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 client.ContainerInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) (client.ContainerInspectResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) client.ContainerInspectResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerInspectOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type MockOperations_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerInspectOptions
func (_e *MockOperations_Expecter) ContainerInspect(ctx any, containerID any, options any) *MockOperations_ContainerInspect_Call {
	return &MockOperations_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID, options)}
}

func (_c *MockOperations_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions)) *MockOperations_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerInspectOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerInspectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_ContainerInspect_Call) Return(containerInspectResult client.ContainerInspectResult, err error) *MockOperations_ContainerInspect_Call {
	_c.Call.Return(containerInspectResult, err)
	return _c
}

func (_c *MockOperations_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error)) *MockOperations_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRemove provides a mock function for the type MockOperations
func (_mock *MockOperations) ContainerRemove(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 client.ContainerRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) client.ContainerRemoveResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerRemoveOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type MockOperations_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerRemoveOptions
func (_e *MockOperations_Expecter) ContainerRemove(ctx any, containerID any, options any) *MockOperations_ContainerRemove_Call {
	return &MockOperations_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, containerID, options)}
}

func (_c *MockOperations_ContainerRemove_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerRemoveOptions)) *MockOperations_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerRemoveOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerRemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_ContainerRemove_Call) Return(containerRemoveResult client.ContainerRemoveResult, err error) *MockOperations_ContainerRemove_Call {
	_c.Call.Return(containerRemoveResult, err)
	return _c
}

func (_c *MockOperations_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)) *MockOperations_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRename provides a mock function for the type MockOperations
func (_mock *MockOperations) ContainerRename(ctx context.Context, containerID string, options client.ContainerRenameOptions) (client.ContainerRenameResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRename")
	}

	var r0 client.ContainerRenameResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRenameOptions) (client.ContainerRenameResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRenameOptions) client.ContainerRenameResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerRenameResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerRenameOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_ContainerRename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRename'
type MockOperations_ContainerRename_Call struct {
	*mock.Call
}

// ContainerRename is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerRenameOptions
func (_e *MockOperations_Expecter) ContainerRename(ctx any, containerID any, options any) *MockOperations_ContainerRename_Call {
	return &MockOperations_ContainerRename_Call{Call: _e.mock.On("ContainerRename", ctx, containerID, options)}
}

func (_c *MockOperations_ContainerRename_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerRenameOptions)) *MockOperations_ContainerRename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerRenameOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerRenameOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_ContainerRename_Call) Return(containerRenameResult client.ContainerRenameResult, err error) *MockOperations_ContainerRename_Call {
	_c.Call.Return(containerRenameResult, err)
	return _c
}

func (_c *MockOperations_ContainerRename_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerRenameOptions) (client.ContainerRenameResult, error)) *MockOperations_ContainerRename_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStart provides a mock function for the type MockOperations
func (_mock *MockOperations) ContainerStart(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 client.ContainerStartResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) (client.ContainerStartResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) client.ContainerStartResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStartResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStartOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type MockOperations_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.ContainerStartOptions
func (_e *MockOperations_Expecter) ContainerStart(ctx any, containerID any, options any) *MockOperations_ContainerStart_Call {
	return &MockOperations_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, containerID, options)}
}

func (_c *MockOperations_ContainerStart_Call) Run(run func(ctx context.Context, containerID string, options client.ContainerStartOptions)) *MockOperations_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStartOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_ContainerStart_Call) Return(containerStartResult client.ContainerStartResult, err error) *MockOperations_ContainerStart_Call {
	_c.Call.Return(containerStartResult, err)
	return _c
}

func (_c *MockOperations_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error)) *MockOperations_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkConnect provides a mock function for the type MockOperations
func (_mock *MockOperations) NetworkConnect(ctx context.Context, networkID string, options client.NetworkConnectOptions) (client.NetworkConnectResult, error) {
	ret := _mock.Called(ctx, networkID, options)

	if len(ret) == 0 {
		panic("no return value specified for NetworkConnect")
	}

	var r0 client.NetworkConnectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.NetworkConnectOptions) (client.NetworkConnectResult, error)); ok {
		return returnFunc(ctx, networkID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.NetworkConnectOptions) client.NetworkConnectResult); ok {
		r0 = returnFunc(ctx, networkID, options)
	} else {
		r0 = ret.Get(0).(client.NetworkConnectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.NetworkConnectOptions) error); ok {
		r1 = returnFunc(ctx, networkID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_NetworkConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkConnect'
type MockOperations_NetworkConnect_Call struct {
	*mock.Call
}

// NetworkConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID string
//   - options client.NetworkConnectOptions
func (_e *MockOperations_Expecter) NetworkConnect(ctx any, networkID any, options any) *MockOperations_NetworkConnect_Call {
	return &MockOperations_NetworkConnect_Call{Call: _e.mock.On("NetworkConnect", ctx, networkID, options)}
}

func (_c *MockOperations_NetworkConnect_Call) Run(run func(ctx context.Context, networkID string, options client.NetworkConnectOptions)) *MockOperations_NetworkConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.NetworkConnectOptions
		if args[2] != nil {
			arg2 = args[2].(client.NetworkConnectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_NetworkConnect_Call) Return(networkConnectResult client.NetworkConnectResult, err error) *MockOperations_NetworkConnect_Call {
	_c.Call.Return(networkConnectResult, err)
	return _c
}

func (_c *MockOperations_NetworkConnect_Call) RunAndReturn(run func(ctx context.Context, networkID string, options client.NetworkConnectOptions) (client.NetworkConnectResult, error)) *MockOperations_NetworkConnect_Call {
	_c.Call.Return(run)
	return _c
}
