package preview

var containerNames = []string{
	"cyberscribe",
	"datamatrix",
	"nexasync",
	"quantumquill",
	"aerosphere",
	"virtuos",
	"fusionflow",
	"neuralink",
	"pixelpulse",
	"synthwave",
	"codecraft",
	"zapzone",
	"robologic",
	"dreamstream",
	"infinisync",
	"megamesh",
	"novalink",
	"xenogenius",
	"ecosim",
	"innovault",
	"techtracer",
	"fusionforge",
	"quantumquest",
	"neuronest",
	"codefusion",
	"datadyno",
	"pixelpioneer",
	"vortexvision",
	"cybercraft",
	"synthsphere",
	"infinitescript",
	"roborhythm",
	"dreamengine",
	"aquasync",
	"geniusgrid",
	"megamind",
	"novasync-pro",
	"xenonwave",
	"ecologic",
	"innoscan",
}

var organizationNames = []string{
	"techwave",
	"codecrafters",
	"innotechlabs",
	"fusionsoft",
	"cyberpulse",
	"quantumscribe",
	"datadynamo",
	"neuralink",
	"pixelpro",
	"synthwizards",
	"virtucorplabs",
	"robologic",
	"dreamstream",
	"novanest",
	"megamind",
	"xenonwave",
	"ecologic",
	"innosync",
	"techgenius",
	"nexasoft",
	"codewave",
	"zapzone",
	"techsphere",
	"aquatech",
	"quantumcraft",
	"neuronest",
	"datafusion",
	"pixelpioneer",
	"synthsphere",
	"infinitescribe",
	"roborhythm",
	"dreamengine",
	"vortexvision",
	"geniusgrid",
	"megamesh",
	"novasync",
	"xenogeniuslabs",
	"ecosim",
	"innovault",
}

var infoMessages = []string{
	"Found new image",
	"Stopping container",
	"Started new container",
	"Stopping linked container",
	"Started linked container",
	"Removing image",
	"Container updated",
	"Detected multiple Watchtower instances - initiating cleanup",
	"Successfully removed all excess Watchtower containers",
	"Image is within cooldown period - not eligible for update",
	"Image age exceeds cooldown - eligible for update",
	"Image creation time unavailable - update check unavailable",
	"Starting HTTP API server",
	"HTTP API server is enabled",
	"Only checking containers in scope",
	"Skipping Watchtower self-update in run-once mode",
	"Watchtower v1.11.7 using Docker API v1.51",
	"Docker image usage budget enabled",
	"Using notifications: gotify",
	"Checking all containers (except explicitly disabled with label)",
	"Update session completed",
}

var warningMessages = []string{
	"Failed to stop container",
	"Failed to remove image",
	"Failed to start new container",
	"Update session failed",
	"Failed to find new image",
	"Failed to list containers",
	"Failed to inspect container",
	"Failed to list containers for image usage check, skipping removal",
	"Docker image usage exceeds configured warning threshold",
}

var errorMessages = []string{
	"Update installation failed. Rolling back to the previous version...",
	"Unable to check for updates. Please check your internet connection.",
	"Update verification failed. Please contact support.",
	"Update package download failed. Try again later.",
	"Failed to stop container",
	"Failed to remove image",
	"Failed to start new container",
	"Update session failed",
	"Failed to find new image",
	"Failed to list containers",
	"Failed to inspect container",
	"Docker image usage exceeds configured maximum",
	"Failed to query Docker image disk usage",
}

var skippedMessages = []string{
	"container skipped: Avoiding potential subscription fees",
	"container skipped: Concerns about update breaking third-party plugins or extensions",
	"container skipped: Avoiding potential changes in licensing terms",
	"container skipped: Concerns about compatibility with other software",
	"container skipped: Fear of losing access to older file formats",
	"container skipped: Prefer the older version's features or design",
	"container skipped: Worries about losing custom settings or configurations",
	"container skipped: Lack of trust in the software developer's updates",
	"container skipped: Don't want to relearn how to use the software",
	"container skipped: Current version works fine for my needs",
	"container skipped: Fear of introducing new bugs",
	"container skipped: Limited bandwidth for downloading updates",
}
