// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Listen provides a mock function for the type MockServer
func (_mock *MockServer) Listen(addr string, config ...fiber.ListenConfig) error {
	var tmpRet mock.Arguments
	if len(config) > 0 {
		tmpRet = _mock.Called(addr, config)
	} else {
		tmpRet = _mock.Called(addr)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...fiber.ListenConfig) error); ok {
		r0 = returnFunc(addr, config...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockServer_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - addr string
//   - config ...fiber.ListenConfig
func (_e *MockServer_Expecter) Listen(addr any, config ...any) *MockServer_Listen_Call {
	return &MockServer_Listen_Call{Call: _e.mock.On("Listen",
		append([]any{addr}, config...)...)}
}

func (_c *MockServer_Listen_Call) Run(run func(addr string, config ...fiber.ListenConfig)) *MockServer_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []fiber.ListenConfig
		var variadicArgs []fiber.ListenConfig
		if len(args) > 1 {
			variadicArgs = args[1].([]fiber.ListenConfig)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockServer_Listen_Call) Return(err error) *MockServer_Listen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Listen_Call) RunAndReturn(run func(addr string, config ...fiber.ListenConfig) error) *MockServer_Listen_Call {
	_c.Call.Return(run)
	return _c
}

// ShutdownWithTimeout provides a mock function for the type MockServer
func (_mock *MockServer) ShutdownWithTimeout(timeout time.Duration) error {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for ShutdownWithTimeout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_ShutdownWithTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownWithTimeout'
type MockServer_ShutdownWithTimeout_Call struct {
	*mock.Call
}

// ShutdownWithTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockServer_Expecter) ShutdownWithTimeout(timeout any) *MockServer_ShutdownWithTimeout_Call {
	return &MockServer_ShutdownWithTimeout_Call{Call: _e.mock.On("ShutdownWithTimeout", timeout)}
}

func (_c *MockServer_ShutdownWithTimeout_Call) Run(run func(timeout time.Duration)) *MockServer_ShutdownWithTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_ShutdownWithTimeout_Call) Return(err error) *MockServer_ShutdownWithTimeout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_ShutdownWithTimeout_Call) RunAndReturn(run func(timeout time.Duration) error) *MockServer_ShutdownWithTimeout_Call {
	_c.Call.Return(run)
	return _c
}
