// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIVersionProvider creates a new instance of MockAPIVersionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIVersionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIVersionProvider {
	mock := &MockAPIVersionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIVersionProvider is an autogenerated mock type for the APIVersionProvider type
type MockAPIVersionProvider struct {
	mock.Mock
}

type MockAPIVersionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIVersionProvider) EXPECT() *MockAPIVersionProvider_Expecter {
	return &MockAPIVersionProvider_Expecter{mock: &_m.Mock}
}

// GetVersion provides a mock function for the type MockAPIVersionProvider
func (_mock *MockAPIVersionProvider) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPIVersionProvider_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockAPIVersionProvider_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockAPIVersionProvider_Expecter) GetVersion() *MockAPIVersionProvider_GetVersion_Call {
	return &MockAPIVersionProvider_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockAPIVersionProvider_GetVersion_Call) Run(run func()) *MockAPIVersionProvider_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIVersionProvider_GetVersion_Call) Return(s string) *MockAPIVersionProvider_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPIVersionProvider_GetVersion_Call) RunAndReturn(run func() string) *MockAPIVersionProvider_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}
