// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/watchtower/pkg/types"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSorter creates a new instance of MockSorter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSorter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSorter {
	mock := &MockSorter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSorter is an autogenerated mock type for the Sorter type
type MockSorter struct {
	mock.Mock
}

type MockSorter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSorter) EXPECT() *MockSorter_Expecter {
	return &MockSorter_Expecter{mock: &_m.Mock}
}

// Sort provides a mock function for the type MockSorter
func (_mock *MockSorter) Sort(log *zerolog.Logger, containers []types.Container, useComposeDependsOn bool) error {
	ret := _mock.Called(log, containers, useComposeDependsOn)

	if len(ret) == 0 {
		panic("no return value specified for Sort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*zerolog.Logger, []types.Container, bool) error); ok {
		r0 = returnFunc(log, containers, useComposeDependsOn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSorter_Sort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sort'
type MockSorter_Sort_Call struct {
	*mock.Call
}

// Sort is a helper method to define mock.On call
//   - log *zerolog.Logger
//   - containers []types.Container
//   - useComposeDependsOn bool
func (_e *MockSorter_Expecter) Sort(log any, containers any, useComposeDependsOn any) *MockSorter_Sort_Call {
	return &MockSorter_Sort_Call{Call: _e.mock.On("Sort", log, containers, useComposeDependsOn)}
}

func (_c *MockSorter_Sort_Call) Run(run func(log *zerolog.Logger, containers []types.Container, useComposeDependsOn bool)) *MockSorter_Sort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(*zerolog.Logger)
		}
		var arg1 []types.Container
		if args[1] != nil {
			arg1 = args[1].([]types.Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSorter_Sort_Call) Return(err error) *MockSorter_Sort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSorter_Sort_Call) RunAndReturn(run func(log *zerolog.Logger, containers []types.Container, useComposeDependsOn bool) error) *MockSorter_Sort_Call {
	_c.Call.Return(run)
	return _c
}
